%YAML:1.0
aruco_bc_nmarkers: 10
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:942, corners:[ [ -1484., -563., 0. ], [ -972., -563., 0. ], [
       -972., -51., 0. ], [ -1484., -51., 0. ] ] }
   - { id:227, corners:[ [ -870., -563., 0. ], [ -358., -563., 0. ], [
       -358., -51., 0. ], [ -870., -51., 0. ] ] }
   - { id:631, corners:[ [ -256., -563., 0. ], [ 256., -563., 0. ], [
       256., -51., 0. ], [ -256., -51., 0. ] ] }
   - { id:861, corners:[ [ 358., -563., 0. ], [ 870., -563., 0. ], [
       870., -51., 0. ], [ 358., -51., 0. ] ] }
   - { id:517, corners:[ [ 972., -563., 0. ], [ 1484., -563., 0. ], [
       1484., -51., 0. ], [ 972., -51., 0. ] ] }
   - { id:537, corners:[ [ -1484., 51., 0. ], [ -972., 51., 0. ], [
       -972., 563., 0. ], [ -1484., 563., 0. ] ] }
   - { id:1008, corners:[ [ -870., 51., 0. ], [ -358., 51., 0. ], [
       -358., 563., 0. ], [ -870., 563., 0. ] ] }
   - { id:939, corners:[ [ -256., 51., 0. ], [ 256., 51., 0. ], [ 256.,
       563., 0. ], [ -256., 563., 0. ] ] }
   - { id:182, corners:[ [ 358., 51., 0. ], [ 870., 51., 0. ], [ 870.,
       563., 0. ], [ 358., 563., 0. ] ] }
   - { id:547, corners:[ [ 972., 51., 0. ], [ 1484., 51., 0. ], [ 1484.,
       563., 0. ], [ 972., 563., 0. ] ] }
